# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 731029b2302432a5cb0a69a8a71031673ddb3e4a1661d9f1810ffad563653c9bf83420ca77b26fe259254e31c2495c7a9ed8d5d2e24a56154616974aa778ca18

test:
  secret_key_base: bc71518efb853e6e1d5128d3929ad7dcd70c32fba6009d01ffec71134754fa8654c5aefe77afb0b0eb31c3f17487d622b6bace86ab997f82ab5c5acb8f24e19d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
